/* Generated By:JavaCC: Do not edit this line. ARAPASCConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ARAPASCConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 7;
  /** RegularExpression Id. */
  int FLOAT_LITERAL = 8;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 9;
  /** RegularExpression Id. */
  int BARNAMEDJ = 10;
  /** RegularExpression Id. */
  int MOUTAGHAIRE = 11;
  /** RegularExpression Id. */
  int BIDAYA = 12;
  /** RegularExpression Id. */
  int NIHAYA = 13;
  /** RegularExpression Id. */
  int INT = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int FLOAT = 16;
  /** RegularExpression Id. */
  int CHAR = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int BREAK = 20;
  /** RegularExpression Id. */
  int CONTINUE = 21;
  /** RegularExpression Id. */
  int ENDIF = 22;
  /** RegularExpression Id. */
  int DO = 23;
  /** RegularExpression Id. */
  int REAPEAT = 24;
  /** RegularExpression Id. */
  int WHILE = 25;
  /** RegularExpression Id. */
  int ENDWHILE = 26;
  /** RegularExpression Id. */
  int FOR = 27;
  /** RegularExpression Id. */
  int ENDFOR = 28;
  /** RegularExpression Id. */
  int PROCEDURE = 29;
  /** RegularExpression Id. */
  int RETURN = 30;
  /** RegularExpression Id. */
  int VOID = 31;
  /** RegularExpression Id. */
  int OUKTOUB = 32;
  /** RegularExpression Id. */
  int IKRAA = 33;
  /** RegularExpression Id. */
  int ADD = 34;
  /** RegularExpression Id. */
  int MIN = 35;
  /** RegularExpression Id. */
  int MUL = 36;
  /** RegularExpression Id. */
  int DIV = 37;
  /** RegularExpression Id. */
  int MODULO = 38;
  /** RegularExpression Id. */
  int ASSIGN = 39;
  /** RegularExpression Id. */
  int ADDONE = 40;
  /** RegularExpression Id. */
  int MINUTEONE = 41;
  /** RegularExpression Id. */
  int LT = 42;
  /** RegularExpression Id. */
  int LE = 43;
  /** RegularExpression Id. */
  int GT = 44;
  /** RegularExpression Id. */
  int GE = 45;
  /** RegularExpression Id. */
  int EQ = 46;
  /** RegularExpression Id. */
  int NE = 47;
  /** RegularExpression Id. */
  int AND = 48;
  /** RegularExpression Id. */
  int OR = 49;
  /** RegularExpression Id. */
  int NOT = 50;
  /** RegularExpression Id. */
  int IDENTIFIER = 51;
  /** RegularExpression Id. */
  int LETTER = 52;
  /** RegularExpression Id. */
  int DIGIT = 53;
  /** RegularExpression Id. */
  int LC = 54;
  /** RegularExpression Id. */
  int RC = 55;
  /** RegularExpression Id. */
  int LM = 56;
  /** RegularExpression Id. */
  int RM = 57;
  /** RegularExpression Id. */
  int LB = 58;
  /** RegularExpression Id. */
  int RB = 59;
  /** RegularExpression Id. */
  int COMMA = 60;
  /** RegularExpression Id. */
  int POINTVERGULE = 61;
  /** RegularExpression Id. */
  int DEUXPOINT = 62;
  /** RegularExpression Id. */
  int POINT = 63;
  /** RegularExpression Id. */
  int GUILLEMET = 64;
  /** RegularExpression Id. */
  int MESSAGE = 65;
  /** RegularExpression Id. */
  int STRING = 66;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<token of kind 6>",
    "<INTEGER_LITERAL>",
    "<FLOAT_LITERAL>",
    "<DECIMAL_LITERAL>",
    "\"Barnamedj\"",
    "\"moutaghaire\"",
    "\"bidaya\"",
    "\"nihaya\"",
    "\"tabiaai\"",
    "\"mantiki\"",
    "\"hakiki\"",
    "\"harref\"",
    "\"ida\"",
    "\"waila\"",
    "\"kherouj\"",
    "\"akmil\"",
    "\"nihaya_ida\"",
    "\"ifaal\"",
    "\"aaide\"",
    "\"madama\"",
    "\"nihaya_madama\"",
    "\"halaka\"",
    "\"nihaya_halaka\"",
    "\"dala\"",
    "\"irjaa\"",
    "\"lachaye\"",
    "\"ouktoub\"",
    "\"ikraa\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"<-\"",
    "\"++\"",
    "\"--\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"tousaoui\"",
    "\"latousaoui\"",
    "\"wa\"",
    "\"aw\"",
    "\"la\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\".\"",
    "\"\\\"\"",
    "<MESSAGE>",
    "<STRING>",
  };

}
